#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_ooking_list:
  path: /api/v1/bookings
  controller: App\Controller\BookingController:indexAction
  methods: [GET]

api_booking:
  path: /api/v1/booking/{id}
  controller: App\Controller\BookingController:findByIdAction


api_booking_create:
  path: /api/v1/bookings
  controller: App\Controller\BookingController:createAction
  methods: [POST]

api_tation_list:
  path: /api/v1/stations
  controller: App\Controller\StationController:indexAction
  methods: [GET]

api_equipment_list:
  path: /api/v1/equipments
  controller: App\Controller\EquipmentController:indexAction
  methods: [GET]

api_van_list:
  path: /api/v1/vans
  controller: App\Controller\VanController:indexAction
  methods: [GET]

api_single_station_status:
  path: /api/v1/station/{id}
  controller: App\Controller\StationDashboardApiController:findByStationAction
